Repository playkuround/playkuround-iOS, pull requests merged in 2024-08, with the labels that each got.

#140 [Setting] #137 - 개발 서버 변경으로 인한 APIManager 수정
  playkuround-iOS/Extensions/Managers/APIManager.swift
Labels: Setting

#142 [Design] #141 - 토스트 메시지 창 디자인 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/toastAlert.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/toastAlert.imageset/toastAlert1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/toastAlert.imageset/toastAlert2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/toastAlert.imageset/toastAlert3x.png
  playkuround-iOS/Views/Root/ToastAlertView.swift
Labels: 호은, UI

#149 [Fix] #148 - TimerBarView에서 글자가 두 줄로 넘어가는 오류 수정
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Views/Games/Common/TimerBarView.swift
Labels: 호은, Fix

#145 [Design] #143 - 프로필 뱃지 선택 창 디자인 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Badge/BadgeImage/badgeChecked.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Badge/BadgeImage/badgeChecked.imageset/badgeChecked1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Badge/BadgeImage/badgeChecked.imageset/badgeChecked2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Badge/BadgeImage/badgeChecked.imageset/badgeChecked3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/profileBadgeBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/profileBadgeBackground.imageset/badgeProfileBackground1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/profileBadgeBackground.imageset/badgeProfileBackground2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/profileBadgeBackground.imageset/badgeProfileBackground3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/ProfileBadgeView.swift
Labels: 호은, UI

#156 [Design] #153 - LandmarkDetailView 디자인 수정사항 반영
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bikeIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bikeIcon.imageset/bikeIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bikeIcon.imageset/bikeIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bikeIcon.imageset/bikeIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bookIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bookIcon.imageset/bookIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bookIcon.imageset/bookIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/bookIcon.imageset/bookIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/cafeIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/cafeIcon.imageset/cafeIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/cafeIcon.imageset/cafeIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/cafeIcon.imageset/cafeIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/certificateIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/certificateIcon.imageset/certificateIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/certificateIcon.imageset/certificateIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/certificateIcon.imageset/certificateIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/convenienceIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/convenienceIcon.imageset/convenienceIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/convenienceIcon.imageset/convenienceIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/convenienceIcon.imageset/convenienceIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/copyIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/copyIcon.imageset/copyIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/copyIcon.imageset/copyIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/copyIcon.imageset/copyIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/kCubeIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/kCubeIcon.imageset/kCubeIcon1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/kCubeIcon.imageset/kCubeIcon2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/AmenityIcon/kCubeIcon.imageset/kCubeIcon3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkDetailLongBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkDetailLongBackground.imageset/landmarkDetailBackgroundNew1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkDetailLongBackground.imageset/landmarkDetailBackgroundNew2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkDetailLongBackground.imageset/landmarkDetailBackgroundNew3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/middleLine.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/middleLine.imageset/middleLine1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/middleLine.imageset/middleLine2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/middleLine.imageset/middleLine3x.png
  playkuround-iOS/Models/Landmark.swift
  playkuround-iOS/Resources/Data/LandmarkDescription.json
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkDetailView.swift
  playkuround-iOS/Views/Home/Landmark/LeadingFlexBox.swift
Labels: 호은, UI

#144 [Fix] #101 - 덕큐피트 게임 로직 수정
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
Labels: 서연, Fix

#160 [Fix] #159 - 게임 중단 및 기타 오류 수정
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
Labels: 호은, Fix

#161 [Feat] #84 - 수강신청 올클릭 게임 로직 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Models/Games/Subject.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickCustomTextView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickTextRainView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 서연, Feat

#165 [Feat] #164 - 학과 2개 추가
  playkuround-iOS/Models/Major.swift
Labels: 호은, Feat

#163 [Feat] #155 - 건쏠지식 게임 밸런스 수정
  playkuround-iOS/Models/Games/Subject.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/QuizGame/QuizBlockView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
Labels: 서연, Feat

#166 [Feat] #133 - 스토리컷 로직 구현
  playkuround-iOS/Models/Story.swift
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/Common/GameResultView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/Views/Story/StoryView.swift
Labels: 서연, Feat

#168 [Refactor] #135 - 게임 밸런스 수정 - 10초 맞추기, 문을 점령해 2종
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Refactor

#167 [Feat] #146 - 프로필 뱃지 선택 기능 구현 및 홈, 랭킹 프로필 이미지 기능 구현
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Models/Badge.swift
  playkuround-iOS/Models/UserEntity.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/Badge/BadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
  playkuround-iOS/Views/Home/ProfileBadgeView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingRow.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
Labels: 호은, Refactor, Feat

#173 [Fix] #172 - BadgeView 열린 뱃지 설명 나오지 않는 오류 수정
  playkuround-iOS/Views/Home/Badge/BadgeView.swift
Labels: 호은, Fix

#177 [Fix] #162 - 게임 카운트다운에서 중단 오류 해결
  playkuround-iOS/ViewModels/GameViewModel.swift
Labels: 호은, Fix

#171 [Feat] #154 - 앱 내 SoundManager를 통해 사운드 적용
  playkuround-iOS/Extensions/Managers/SoundManager.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/Common/GamePauseView.swift
  playkuround-iOS/Views/Games/Common/GameResultView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
  playkuround-iOS/Views/Home/Adventure/AdventureView.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Home/Badge/BadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkDetailView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Map/MapView.swift
  playkuround-iOS/Views/MyPage/CheckLogoutView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
  playkuround-iOS/Views/Register/RegisterMajorView.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
  playkuround-iOS/Views/Register/TermsView.swift
  playkuround-iOS/Views/Root/RequestPermissionView.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/Views/Story/StoryView.swift
  playkuround-iOS/playkuround_iOSApp.swift
Labels: 서연, Feat

#178 [Fix] #174 - 건쏠지식 점수 로직 수정 (1.5v)
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
Labels: 서연, Fix

#180 [Design] #179 - 10초를 맞춰봐 게임 디자인 수정
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeFailed.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeFailed.imageset/timeFailed1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeFailed.imageset/timeFailed2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeFailed.imageset/timeFailed3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
Labels: 호은, UI, Fix

#176 [Feat] #170 - APIManager에서 새 뱃지, 토스트 메시지 처리 구현
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/MapViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/Common/GameResultView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Home/Adventure/AdventureView.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Home/Badge/BadgeView.swift
  playkuround-iOS/Views/Home/Badge/NewBadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkDetailView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkView.swift
  playkuround-iOS/Views/Home/ProfileBadgeView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Map/MapView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Root/NetworkErrorView.swift
  playkuround-iOS/Views/Root/RequestPermissionView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Network, Feat

#187 [Fix] #175 - 10초를 맞춰봐 변경된 게임 로직에 따른 사운드 수정
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
Labels: 서연, Fix

#188 [Fix] #186 - 닉네임 등록뷰에서 다음 버튼 클릭 시 효과음 나올 수 있도록 수정
  playkuround-iOS/Views/Register/RegisterNickname.swift
Labels: 서연, Fix

#183 [Design] #182 - 공지사항 버튼 및 뷰 디자인 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiLongBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiLongBackground.imageset/notiLongBackground1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiLongBackground.imageset/notiLongBackground2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiLongBackground.imageset/notiLongBackground3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiShortBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiShortBackground.imageset/notiShortBackground1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiShortBackground.imageset/notiShortBackground2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Notification/notiShortBackground.imageset/notiShortBackground3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/notiButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/notiButton.imageset/notiButton1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/notiButton.imageset/notiButton2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/notiButton.imageset/notiButton3x.png
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Notification/NotificationView.swift
  playkuround-iOS/Views/Home/Notification/WebView.swift
Labels: 호은, UI

#192 [Fix] #191 - NotificationView 내 오류 코드 수정
  playkuround-iOS/Views/Home/Notification/NotificationView.swift
Labels: 호은, Fix

#194 [Setting] #193 - 릴리즈용 기능 수정
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/Badge/NewBadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
Labels: 호은, Setting, Fix, Feat

#200 [Fix] #199 - 뱃지 프로필 선택 창 잠긴 뱃지 숨기기 작업
  playkuround-iOS/Views/Home/Badge/ProfileBadgeView.swift
Labels: 호은, Fix

#203 [Feat] #198 - 서버 공지사항 API 연동 및 새 공지 기능 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Extensions/Managers/EventManager.swift
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Notification/NotificationView.swift
Labels: 호은, Network, Feat

#204 [Feat] #202 - 심사용 예외 처리 및 릴리즈 준비 작업
  .gitignore
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/AdminAccount.swift
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/MapViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Home/Badge/ProfileBadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
Labels: 호은, Feat

#206 [Fix] #205 - 심사용 계정 예외 처리 추가 구현
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/Views/Login/LoginView.swift
Labels: 호은, Fix

#208 [Feat] #207 - 계정 삭제 기능 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Extensions/Managers/GAManager.swift
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/MyPage/CheckDeleteAccountView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
Labels: 호은, Feat

#212 [Fix] #210 - QA 우선 기능적 수정사항 1차 반영
  playkuround-iOS/Models/Landmark.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Fix, Feat

#220 [Fix] #219 - 랜드마크 index out of range 오류 수정
  playkuround-iOS/Models/Landmark.swift
  playkuround-iOS/Views/Map/MapView.swift
Labels: 호은, Fix

#222 [Design] #221 - 게임 종료 후 3초 대기 및 건쏠지식 3초 대기 뷰 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/Common/GameWaitingView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
Labels: 호은, Feat

#231 [Fix] #230 - UserEntity 객체 Attribute 오류 수정
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Models/UserEntity.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/MyPage/MyPageProfileView.swift
Labels: 호은, Feat

#226 [Fix] #214 - QA 10초를 맞춰봐, 덕쿠를 잡아라 게임 수정사항 반영
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
Labels: 호은, Fix

#232 [Fix] #223 - 수강신청 ALL 클릭 QA 반영
  playkuround-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  playkuround-iOS/Views/Games/AllClickGame/AllClickCustomTextView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameView.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickTextRainView.swift
Labels: 서연, Fix

#233 [Feat] #227 - Server Healthy 체크 및 업데이트 알림 로직 적용
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Root/NetworkErrorView.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/Views/Root/UserAlarmView.swift
Labels: 호은, Feat

#235 [Feat] #225 - MapView 지도 Span, Bound 제한 적용
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Map/MapView.swift
Labels: 호은, Feat

#238 [Chore] #237 - Marketing Version을 2.0.5로 변경
  playkuround-iOS.xcodeproj/project.pbxproj
Labels: 서연, Chore

#236 [Fix] #234 - 로그인 QA 반영
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/UIApplication+.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Login/LoginView.swift
Labels: 호은, Fix

#240 [Fix] #239 - 이메일 인증번호 틀린 후 확인 버튼 반응 없는 오류 수정
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
Labels: 호은, Fix
