Repository playkuround/playkuround-iOS, pull requests merged in 2024-03, with the labels that each got.

#2 [Setting] #1 - 프로젝트 초기 세팅
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/AppIcon.appiconset/1024.png
  playkuround-iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuBackground.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuBlue1.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuBlue2.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuBrown.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuDarkBlue.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuDarkGreen.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuGray1.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuGray2.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuLightGreen.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuRed.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuText.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuTimebarGreen.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuTimebarOrange.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuTimebarRed.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuYellow.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonBlue.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonBlue.imageset/longButtonBlue.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonDarkBlue.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonDarkBlue.imageset/longButtonDarkBlue.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonDarkGray.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonDarkGray.imageset/longButtonDarkGray.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonGray.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonGray.imageset/longButtonGray.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonWhite.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/longButtonWhite.imageset/longButtonWhite.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonBlue.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonBlue.imageset/shortButtonBlue.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonDarkBlue.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonDarkBlue.imageset/shortButtonDarkBlue.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonDarkGray.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonDarkGray.imageset/shortButtonDarkGray.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonGray.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/shortButtonGray.imageset/shortButtonGray.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/smallButtonBlue.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/smallButtonBlue.imageset/smallButtonBlue.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Contents.json
  playkuround-iOS/Info.plist
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/Fonts/NeoDunggeunmoPro-Regular.ttf
  playkuround-iOS/Resources/Fonts/Pretendard-Regular.otf
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/ContentView.swift
  playkuround-iOS/Views/Login/LoginView.swift
Labels: 서연, Setting

#5 [Design] #3 - MainView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainLogo.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainLogo.imageset/mainLogo.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainLogo.imageset/mainLogo@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainLogo.imageset/mainLogo@3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Main/MainView.swift
Labels: 서연, UI

#8 [Fix] #7 - MainView 기능명세서 기반으로 수정
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground.imageset/mainBackground@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground1.imageset/mainBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground2.imageset/mainBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground3.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground3.imageset/mainBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground4.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Main/mainBackground4.imageset/mainBackground4.png
  playkuround-iOS/Resources/AnimationCustomView.swift
  playkuround-iOS/Views/Main/MainView.swift
Labels: 서연, UI, Fix

#10 [Setting] #9 - Badge, Major, UserNotification, ScoreType 구조화 작업
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Models/Badge.swift
  playkuround-iOS/Models/Major.swift
  playkuround-iOS/Models/ScoreType.swift
  playkuround-iOS/Models/UserNotification.swift
Labels: 호은, Setting

#12 [Feat] #4 - 서버 통신 관련 Extensions 개발 (1차)
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/APIManager.swift
  playkuround-iOS/Extensions/NetworkManager.swift
Labels: 호은, Feat

#14 [Setting] #11 - Haptic, SoundManager 세팅
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Extensions/Managers/HapticManager.swift
  playkuround-iOS/Extensions/Managers/NetworkManager.swift
  playkuround-iOS/Extensions/Managers/SoundManager.swift
  playkuround-iOS/Resources/AnimationCustomView.swift
  playkuround-iOS/Resources/Sounds/Card/cardAllCorrect.mp3
  playkuround-iOS/Resources/Sounds/Card/cardClicked.mp3
  playkuround-iOS/Resources/Sounds/Card/cardCorrect.mp3
  playkuround-iOS/Resources/Sounds/Card/cardIncorrect.mp3
  playkuround-iOS/Resources/Sounds/ClassRegistration/classCorrect.mp3
  playkuround-iOS/Resources/Sounds/ClassRegistration/classEnd.mp3
  playkuround-iOS/Resources/Sounds/ClassRegistration/classMinusHeart.mp3
  playkuround-iOS/Resources/Sounds/Cupid/cupidBad.mp3
  playkuround-iOS/Resources/Sounds/Cupid/cupidGoodOrPerfect.mp3
  playkuround-iOS/Resources/Sounds/Duckku/blackDuckkuClicked.mp3
  playkuround-iOS/Resources/Sounds/Duckku/duckkuClicked.mp3
  playkuround-iOS/Resources/Sounds/Duckku/duckkuWindowOpenAndClose.mp3
  playkuround-iOS/Resources/Sounds/Microbe/microbeEnd.mp3
  playkuround-iOS/Resources/Sounds/Microbe/microbeHit.mp3
  playkuround-iOS/Resources/Sounds/Moon/moonClicked.mp3
  playkuround-iOS/Resources/Sounds/Moon/moonHundredClicked.mp3
  playkuround-iOS/Resources/Sounds/Quiz/quizCorrect.mp3
  playkuround-iOS/Resources/Sounds/Quiz/quizIncorrect.mp3
  playkuround-iOS/Resources/Sounds/Timer/timerButtonClicked.mp3
  playkuround-iOS/Resources/Sounds/Timer/timerCorrect.mp3
  playkuround-iOS/Resources/Sounds/Timer/timerIncorrect.mp3
  playkuround-iOS/Resources/Sounds/backgroundMusic.mp3
  playkuround-iOS/Resources/Sounds/buttonClicked.mp3
Labels: 서연, Setting

#17 [Design] #16 - RegisterView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/closeButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/closeButton.imageset/closeButton.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuBackground.imageset/menuBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuButton.imageset/menuButton.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuDownArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuDownArrow.imageset/menuDownArrow.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuItem.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuItem.imageset/menuItem.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuUpArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuUpArrow.imageset/menuUpArrow.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/selectedMenuItem.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/selectedMenuItem.imageset/selectedMenuItem.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/blackCheck.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/blackCheck.imageset/blackCheck.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/grayLine.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/grayLine.imageset/grayLine.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/rightBlackArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/rightBlackArrow.imageset/rightBlackArrow.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/rightWhiteArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/rightWhiteArrow.imageset/rightWhiteArrow.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/whiteCheck.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/whiteCheck.imageset/whiteCheck.svg
  playkuround-iOS/Models/Major.swift
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Resources/Texts/location.txt
  playkuround-iOS/Resources/Texts/privacy.txt
  playkuround-iOS/Resources/Texts/service.txt
  playkuround-iOS/Views/Register/RegisterMajorView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
  playkuround-iOS/Views/Register/TermsView.swift
Labels: 호은, UI

#18 [Design] #6 - LoginView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Login/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Login/bottomSheetBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Login/bottomSheetBackground.imageset/bottomSheetBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Login/bottomSheetBackground.imageset/bottomSheetBackground@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Login/bottomSheetBackground.imageset/bottomSheetBackground@3x.png
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/AuthenticationTimerView.swift
  playkuround-iOS/Views/Login/LoginBottomSheetView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
Labels: 서연, UI

#23 [Fix] #22 - Font 파일 내 상수 중복 정의 오류 수정
  playkuround-iOS/Resources/Font.swift
Labels: 호은, Fix

#25 [Fix] #24 - APIManager 토큰 없이 특정 API 호출 실패하는 오류 수정
  playkuround-iOS/Extensions/Managers/APIManager.swift
Labels: 호은, Fix

#27 [Fix] #26 - RegisterView 오류 수정 및 Image Asset 파일 SVG로 변경
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/closeButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/closeButton.imageset/closeButton.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Button/closeButton.imageset/closeButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuBackground.imageset/menuBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuBackground.imageset/menuBackground.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuButton.imageset/menuButton.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuButton.imageset/menuButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuItem.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuItem.imageset/menuItem.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuItem.imageset/menuItem.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuUpArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuUpArrow.imageset/menuUpArrow.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/menuUpArrow.imageset/menuUpArrow.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/selectedMenuItem.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/selectedMenuItem.imageset/selectedMenuItem.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Menu/selectedMenuItem.imageset/selectedMenuItem.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/grayLine.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/grayLine.imageset/grayLine.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Register/grayLine.imageset/grayLine.svg
  playkuround-iOS/Views/Register/RegisterMajorView.swift
Labels: 호은, Fix

#28 [Fix] #21 - 회원가입 관련 뷰 버튼 구현 방식 수정 및 자간 적용
  playkuround-iOS/Views/Register/RegisterMajorView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
Labels: 호은, Fix

#32 [Design] #31 - Loading 및 NetworkError 뷰 디자인
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack1.imageset/loadingBlack1.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack2.imageset/loadingBlack2.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack3.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingBlack3.imageset/loadingBlack3.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite1.imageset/loadingWhite1.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite2.imageset/loadingWhite2.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite3.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingWhite3.imageset/loadingWhite3.svg
  playkuround-iOS/Resources/Images/AnimationImages.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Root/LoadingView.swift
  playkuround-iOS/Views/Root/NetworkErrorView.swift
Labels: 호은, UI

#34 [Fix] #33 - project.pbxproj 파일 conflict 오류 수정
  playkuround-iOS.xcodeproj/project.pbxproj
Labels: 호은, Fix

#35 [Feat] #19 - LoginView API 연결 및 뷰 내 로직 연결
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/AuthenticationTimer.swift
  playkuround-iOS/Views/Login/LoginBottomSheetView.swift
  playkuround-iOS/Views/Login/LoginView.swift
Labels: 서연, Network, Feat

#38 [Feat] #37 - ViewModifier을 이용한 Custom NaivgationBar 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/View+.swift
  playkuround-iOS/Extensions/ViewModifiers/NavigationBarModifier.swift
Labels: 서연, UI, Feat

#42 [Design] #36 - MypageView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ColorAssets/kuBlue3.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCheer1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCheer1.imageset/dance2 (1).png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCheer2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCheer2.imageset/dance3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCurrentScore.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCurrentScore.imageset/mypageCurrentScore.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCurrentScore.imageset/mypageCurrentScore@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageCurrentScore.imageset/mypageCurrentScore@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageHighestScore.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageHighestScore.imageset/mypageHighestScore.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageHighestScore.imageset/mypageHighestScore@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/MyPage/mypageHighestScore.imageset/mypageHighestScore@3x.png
  playkuround-iOS/Resources/Images/AnimationImages.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/MyPage/CheckLogoutView.swift
  playkuround-iOS/Views/MyPage/CheerPKTeamView.swift
  playkuround-iOS/Views/MyPage/MyPageListRowView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/MyPage/MyPageProfileView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
Labels: 서연, UI

#45 [Feat] #20 - RootView 구현 및 로그인 및 회원가입 flow 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Loading/loadingIcon.imageset/loadingIcon.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/messageBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/messageBackground.imageset/messageBackground1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/messageBackground.imageset/messageBackground2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/messageBackground.imageset/messageBackground3x.png
  playkuround-iOS/Info.plist
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/Fonts/Pretendard-Bold.otf
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/LoginBottomSheetView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Register/RegisterMajorView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
  playkuround-iOS/Views/Root/NetworkErrorView.swift
  playkuround-iOS/Views/Root/RequestPermissionView.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/playkuround_iOSApp.swift
Labels: 호은, Network, Fix, Feat

#53 [Setting] #52 - Landmark 데이터 추가 및 랜드마크 API 작업
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Models/Landmark.swift
  playkuround-iOS/ViewModels/MapViewModel.swift
Labels: 호은, Setting, Network

#50 [Design] #46 - 일시정지뷰, 카운트다운 뷰, 10초를 맞춰봐 게임 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ColorAssets/kuGreen.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ColorAssets/kuLightYellowBackground.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/beigePauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/beigePauseButton.imageset/beigePauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/bluePauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/bluePauseButton.imageset/bluePauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/bronzePauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/bronzePauseButton.imageset/bronzePauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/brownPauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/brownPauseButton.imageset/brownPauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/grayPauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/grayPauseButton.imageset/grayPauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/lightBrownPauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/lightBrownPauseButton.imageset/lightBrownPauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/yellowPauseButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Button/yellowPauseButton.imageset/yellowPauseButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown1.imageset/countdown1.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown2.imageset/countdown2.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown3.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Countdown/countdown3.imageset/countdown3.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeBackground.imageset/clockBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timePlayButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timePlayButton.imageset/timerPlayButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timePlayButtonPressed.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timePlayButtonPressed.imageset/timerStartButtonPressed.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeRestartButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeRestartButton.imageset/timerRestartButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeRestartButtonPressed.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeRestartButtonPressed.imageset/timerRestartButtonPressed.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeStopButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeStopButton.imageset/timerStopButton.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeStopButtonPressed.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeStopButtonPressed.imageset/timerStopButtonPressed.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon1.imageset/timeSuccess1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon2.imageset/timeSuccess2.png
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/Images/AnimationImages.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/CountdownView.swift
  playkuround-iOS/Views/Games/GamePauseView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
Labels: 호은, UI

#51 [Feat] #41 - MyPageView 뷰 연결 및 API 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/leftBlackArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/leftBlackArrow.imageset/leftBlackArrow.svg
  playkuround-iOS/Extensions/Managers/APIManager.swift
  playkuround-iOS/Models/UserEntity.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/MyPage/CheckLogoutView.swift
  playkuround-iOS/Views/MyPage/CheerPKTeamView.swift
  playkuround-iOS/Views/MyPage/MyPageListRowView.swift
  playkuround-iOS/Views/MyPage/MyPageListSectionView.swift
  playkuround-iOS/Views/MyPage/MyPageProfileView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 서연, Network, Feat

#57 [Design] #56 - TimerBarView 및 게임 결과창 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/resultBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/resultBackground.imageset/resultBackgroundx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/resultBackground.imageset/resultBackgroundx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/resultBackground.imageset/resultBackgroundx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/scoreBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/scoreBackground.imageset/scoreBackgroundx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/scoreBackground.imageset/scoreBackgroundx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Result/scoreBackground.imageset/scoreBackgroundx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarBackground.imageset/timerBarBackground.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarBackgroundBlack.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarBackgroundBlack.imageset/timerBarBackgroundBlack.svg
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarIcon.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/TimerBar/timerBarIcon.imageset/timerBarIcon.svg
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/CountdownView.swift
  playkuround-iOS/Views/Games/GameResultView.swift
  playkuround-iOS/Views/Games/TimerBarView.swift
Labels: 호은, UI
