Repository playkuround/playkuround-iOS, pull requests merged in 2024-09, with the labels that each got.

#242 [Feat] #241 - 앱 강제 업데이트 로직 적용
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/updateBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/updateBackground.imageset/updateBackground1x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/updateBackground.imageset/updateBackground2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/updateBackground.imageset/updateBackground3x.png
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/Views/Root/UpdateRequestView.swift
Labels: 호은, Feat

#244 [Fix] #243 - 랜드마크 랭킹 뷰 폰트 깨짐 수정
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
Labels: 호은, Fix

#246 [Fix] #245 - QA 우선 기능적 수정사항 3차 반영
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/Views/Games/AllClickGame/AllClickGameViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
  playkuround-iOS/Views/Games/Common/GamePauseView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameEntity.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/MyPage/CheckDeleteAccountView.swift
  playkuround-iOS/Views/Register/RegisterMajorView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
Labels: 호은, Fix

#247 [Fix] #224 - 덕큐피트 QA 반영
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Views/Games/CupidGame/CupidEntity.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
Labels: 호은, Fix, Refactor

#249 [Chore] #248 - 앱 업데이트를 위한 Marketing Version 2.1.0으로 변경
  playkuround-iOS.xcodeproj/project.pbxproj
Labels: 서연, Chore

#251 [Fix] #250 - QA 수정사항 4차 반영
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/MyPage/MyPageProfileView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
  playkuround-iOS/Views/Root/RootView.swift
  playkuround-iOS/Views/Root/ToastAlertView.swift
Labels: 호은, Fix

#255 [Fix] #254 - QA 수정사항 5차 반영
  playkuround-iOS/Extensions/Managers/MotionManager.swift
  playkuround-iOS/Resources/Localizable.xcstrings
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Home/HomeView.swift
Labels: 호은, Fix

#257 [Chore] #256 - Marketing Version 2.1.1로 변경
  playkuround-iOS.xcodeproj/project.pbxproj
Labels: 서연, Chore

#259 [Fix] #258 - 일감호에서 살아남기 생명 깎이지 않는 오류 수정
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
Labels: 호은, Fix

#253 [Feat] #169 - 애니메이션 및 로딩 UX 개선
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Home/Badge/ProfileBadgeView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Login/AuthenticationCodeView.swift
  playkuround-iOS/Views/Login/LoginView.swift
  playkuround-iOS/Views/Main/MainView.swift
  playkuround-iOS/Views/Register/RegisterNickname.swift
  playkuround-iOS/Views/Register/RegisterTermsView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, UI, Refactor, Feat
