Repository playkuround/playkuround-iOS, pull requests merged in 2024-05, with the labels that each got.

#83 [Fix] #79 - 건쏠지식 문제 안보이는 오류 수정
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
Labels: 서연, Fix

#87 [Design] #77 - 일감호에서 살아남기 게임 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBackground.imageset/surviveBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBackground.imageset/surviveBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBackground.imageset/surviveBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBug.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBug.imageset/surviveBug1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBug.imageset/surviveBug2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBug.imageset/surviveBug3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckku.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckku.imageset/surviveDuckku1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckku.imageset/surviveDuckku2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckku.imageset/surviveDuckku3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckkuHit.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckkuHit.imageset/surviveDuckkuHit1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckkuHit.imageset/surviveDuckkuHit2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveDuckkuHit.imageset/surviveDuckkuHit3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeart.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeart.imageset/surviveHeart1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeart.imageset/surviveHeart2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeart.imageset/surviveHeart3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeartBroken.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeartBroken.imageset/surviveHeartBroken1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeartBroken.imageset/surviveHeartBroken2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveHeartBroken.imageset/surviveHeartBroken3.png
  playkuround-iOS/Models/Games/WindowComponent.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameEntityView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, UI

#88 [Feat] #82 - 덕큐피트 게임 로직 구현
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
Labels: 서연, Feat

#92 [Feat] #90 - 덕쿠를 잡아라 게임 로직 구현
  playkuround-iOS/Models/Games/Window.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameView.swift
  playkuround-iOS/Views/Games/CatchGame/CatchGameViewModel.swift
  playkuround-iOS/Views/Games/Common/GameResultView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Feat

#97 [Fix] #95 - 책뒤집기 카트 셔플 오류 수정
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
Labels: 호은, Fix

#99 [Design] #94 - AttendanceView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/attendanceBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/attendanceBackground.imageset/attendanceBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/attendanceBackground.imageset/attendanceBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/attendanceBackground.imageset/attendanceBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarBox.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarBox.imageset/calendarBox1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarBox.imageset/calendarBox2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarBox.imageset/calendarBox3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarTodayBox.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarTodayBox.imageset/calendarTodayBox1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarTodayBox.imageset/calendarTodayBox2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Attendance/calendarTodayBox.imageset/calendarTodayBox3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBackground.imageset/homeBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBackground.imageset/homeBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBackground.imageset/homeBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/leftWhiteArrow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Root/leftWhiteArrow.imageset/leftWhiteArrow.svg
  playkuround-iOS/Extensions/Date+.swift
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, UI

#96 [Feat] #91 - 일감호에서 살아남기 게임 로직 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoat3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoatHorizontal1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoatHorizontal2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Survive/surviveBoat.imageset/surviveBoatHorizontal3.png
  playkuround-iOS/Extensions/Managers/MotionManager.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameEntity.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameEntityView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameView.swift
  playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Feat
