Repository playkuround/playkuround-iOS, pull requests merged in 2024-06, with the labels that each got.

#102 [Design] #98 - MapView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/landmarkFlag.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/landmarkFlag.imageset/landmarkFlag1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/landmarkFlag.imageset/landmarkFlag2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/landmarkFlag.imageset/landmarkFlag3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotation.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotation.imageset/userAnnotation1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotation.imageset/userAnnotation2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotation.imageset/userAnnotation3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotationHeading.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotationHeading.imageset/userHeading1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotationHeading.imageset/userHeading2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Map/userAnnotationHeading.imageset/userHeading3.png
  playkuround-iOS/Models/Landmark.swift
  playkuround-iOS/Views/Map/AnnotationWrapper.swift
  playkuround-iOS/Views/Map/CustomMapAnnotationView.swift
  playkuround-iOS/Views/Map/MapView.swift
Labels: 호은, UI

#105 [Feat] #100 - HomeViewModel 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/HomeViewModel.swift
Labels: 호은, Feat

#109 [Design] #103 - HomeView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/attendanceButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/attendanceButton.imageset/attendanceButton1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/attendanceButton.imageset/attendanceButton2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/attendanceButton.imageset/attendanceButton3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeBackground.imageset/badgeRankingBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeBackground.imageset/badgeRankingBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeBackground.imageset/badgeRankingBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeButton.imageset/badgeButton1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeButton.imageset/badgeButton2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/badgeButton.imageset/badgeButton3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBorder.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBorder.imageset/homeBorder1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBorder.imageset/homeBorder2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/homeBorder.imageset/homeBorder3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/myPageButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/myPageButton.imageset/myPageButton1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/myPageButton.imageset/myPageButton2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/myPageButton.imageset/myPageButton3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingBackground.imageset/homeRankingBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingBackground.imageset/homeRankingBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingBackground.imageset/homeRankingBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingButton.imageset/rankingButton1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingButton.imageset/rankingButton2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/rankingButton.imageset/rankingButton3.png
  playkuround-iOS/Resources/Font.swift
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Home/HomeView.swift
Labels: 호은, UI

#110 [Feat] #108 - HomeView 및 하위 View에 HomeViewModel 연결
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Home/AttendanceView.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkDetailView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkView.swift
  playkuround-iOS/Views/Map/MapView.swift
  playkuround-iOS/Views/MyPage/MyPageView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Network, Feat

#113 [Design] #112 - 전체랭킹뷰 (TotalRankingView) UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBackground.imageset/rankingBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBackground.imageset/rankingBackground@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBackground.imageset/rankingBackground@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBronze.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBronze.imageset/rankingBronze.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBronze.imageset/rankingBronze@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingBronze.imageset/rankingBronze@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingGold.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingGold.imageset/rankingGold.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingGold.imageset/rankingGold@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingGold.imageset/rankingGold@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformation.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformation.imageset/rankinigInformation.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformation.imageset/rankinigInformation@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformation.imageset/rankinigInformation@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformationButton.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformationButton.imageset/rankingInformationButton.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformationButton.imageset/rankingInformationButton@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingInformationButton.imageset/rankingInformationButton@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingMineRow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingMineRow.imageset/rankingMineRow.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingMineRow.imageset/rankingMineRow@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingMineRow.imageset/rankingMineRow@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingSilver.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingSilver.imageset/rankingSilver.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingSilver.imageset/rankingSilver@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingSilver.imageset/rankingSilver@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTable.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTable.imageset/rankingTable.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTable.imageset/rankingTable@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTable.imageset/rankingTable@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTitleRow.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTitleRow.imageset/rankingTitleRow.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTitleRow.imageset/rankingTitleRow@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/TotalRanking/rankingTitleRow.imageset/rankingTitleRow@3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/HomeView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingInformationView.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingRow.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
Labels: 서연, UI

#116 [Feat] #114 - BadgeView 로직 적용 및 서버 연결
  playkuround-iOS/Models/Badge.swift
  playkuround-iOS/Views/Home/Badge/BadgeDetailView.swift
  playkuround-iOS/Views/Home/Badge/BadgeView.swift
Labels: 서연, Network, Feat

#119 [Fix] #118 - BadgeDetailView 내 이미지 파일 수정
  playkuround-iOS/Views/Home/Badge/BadgeDetailView.swift
Labels: 서연, Fix

#117 [Feat] #115 - TotalRankingView 로직 적용 및 서버 연결
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Extensions/Formatter+.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingRow.swift
  playkuround-iOS/Views/Home/TotalRanking/TotalRankingView.swift
Labels: 서연, Network, Feat

#121 [Design] #120 - Landmark Ranking View UI 개발
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ColorAssets/kuTextDarkGreen.colorset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingBackground.imageset/landmarkRankingBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingBackground.imageset/landmarkRankingBackgroundx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingBackground.imageset/landmarkRankingBackgroundx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingFrame.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingFrame.imageset/landmarkRankingFrame1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingFrame.imageset/landmarkRankingFrame2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkRankingFrame.imageset/landmarkRankingFrame3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkScoreBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkScoreBackground.imageset/landmarkScoreBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkScoreBackground.imageset/landmarkScoreBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Landmark/landmarkScoreBackground.imageset/landmarkScoreBackground3.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkView.swift
Labels: 호은, UI

#124 [Design] #123 - AdventureView UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureBackground.imageset/adventureBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureBackground.imageset/adventureBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureBackground.imageset/adventureBackground3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureFrame.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureFrame.imageset/adventureFrame1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureFrame.imageset/adventureFrame2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/adventureFrame.imageset/adventureFrame3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/rouletteBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/rouletteBackground.imageset/rouletteBackground1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/rouletteBackground.imageset/rouletteBackground2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Home/Adventure/rouletteBackground.imageset/rouletteBackground3.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Home/Adventure/AdventureView.swift
Labels: 호은, UI

#125 [Setting] #122 - 프로젝트 플랫폼 및 화면 모드 세팅
  playkuround-iOS.xcodeproj/project.pbxproj
Labels: 호은, Setting

#128 [Feat] #127 - LandmarkRankingView 로직 구현 및 서버 연결
  playkuround-iOS/Models/UserEntity.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/Views/Home/Landmark/LandmarkRankingView.swift
Labels: 호은, Network, Feat

#129 [Feat] #126 - AdventureView 로직 적용
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/HomeViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Home/Adventure/AdventureView.swift
  playkuround-iOS/Views/Home/HomeView.swift
Labels: 호은, Feat
