Repository playkuround/playkuround-iOS, pull requests merged in 2024-04, with the labels that each got.

#58 [Design] #55 - MOON을 점령해 게임 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon1.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon1.imageset/moon1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon1.imageset/moon1@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon1.imageset/moon1@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon2.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon2.imageset/moon2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon2.imageset/moon2@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon2.imageset/moon2@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon3.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon3.imageset/moon3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon3.imageset/moon3@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon3.imageset/moon3@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon4.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon4.imageset/moon4.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon4.imageset/moon4@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moon4.imageset/moon4@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moonBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moonBackground.imageset/moonBackground.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moonBackground.imageset/moonBackground@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Moon/moonBackground.imageset/moonBackground@3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
Labels: 서연, UI

#61 [Design] #60 - 책 뒤집기 게임 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/bullCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/bullCard.imageset/bullCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/bullCard.imageset/bullCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/bullCard.imageset/bullCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/cardBackground.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/cardBackground.imageset/cardBackgroundx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/cardBackground.imageset/cardBackgroundx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/cardBackground.imageset/cardBackgroundx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/catCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/catCard.imageset/catCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/catCard.imageset/catCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/catCard.imageset/catCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/flowerCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/flowerCard.imageset/flowerCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/flowerCard.imageset/flowerCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/flowerCard.imageset/flowerCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/frontCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/frontCard.imageset/frontCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/frontCard.imageset/frontCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/frontCard.imageset/frontCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/gooseCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/gooseCard.imageset/gooseCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/gooseCard.imageset/gooseCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/gooseCard.imageset/gooseCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/lakeCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/lakeCard.imageset/lakeCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/lakeCard.imageset/lakeCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/lakeCard.imageset/lakeCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/milkCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/milkCard.imageset/milkCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/milkCard.imageset/milkCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/milkCard.imageset/milkCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/sideCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/sideCard.imageset/sideCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/sideCard.imageset/sideCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/sideCard.imageset/sideCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/treeCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/treeCard.imageset/treeCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/treeCard.imageset/treeCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/treeCard.imageset/treeCardx3.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/turtleCard.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/turtleCard.imageset/turtleCardx1.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/turtleCard.imageset/turtleCardx2.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Card/turtleCard.imageset/turtleCardx3.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/Views/Games/CardGame/Card.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardView.swift
Labels: 호은, UI

#62 [Feat] #49 - GameViewModel 개발
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/Views/Games/Common/CountdownView.swift
  playkuround-iOS/Views/Games/Common/GamePauseView.swift
  playkuround-iOS/Views/Games/Common/GameResultView.swift
  playkuround-iOS/Views/Games/Common/TimerBarView.swift
Labels: 호은, Setting, Network, Feat

#65 [Feat] #63 - 책 뒤집기 게임 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Models/Games/CardComponent.swift
  playkuround-iOS/Resources/AnimationCustomView.swift
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardGameView.swift
  playkuround-iOS/Views/Games/CardGame/CardGameViewModel.swift
  playkuround-iOS/Views/Games/CardGame/CardView.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Feat

#66 [Feat] #64 - 10초를 맞춰봐 게임 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
  playkuround-iOS/Views/Games/TimerGame/TimerGameViewModel.swift
  playkuround-iOS/Views/Games/TimerGame/TimerState.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 호은, Feat

#69 [Feat] #68 - MOON을 점령해 게임 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameView.swift
  playkuround-iOS/Views/Games/MoonGame/MoonGameViewModel.swift
  playkuround-iOS/Views/Games/MoonGame/MoonState.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 서연, Feat

#78 [Design] #72 - 덕큐피트 게임 UI 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackGround.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackGround.imageset/cupidBackGround.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackGround.imageset/cupidBackGround@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackGround.imageset/cupidBackGround@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackgroundBridge.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackgroundBridge.imageset/cupidBackgroundBridge.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackgroundBridge.imageset/cupidBackgroundBridge@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBackgroundBridge.imageset/cupidBackgroundBridge@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBad.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBad.imageset/cupidBad.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBad.imageset/cupidBad@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidBad.imageset/cupidBad@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuBlack.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuBlack.imageset/cupidDuckkuBlack.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuBlack.imageset/cupidDuckkuBlack@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuBlack.imageset/cupidDuckkuBlack@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuWhite.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuWhite.imageset/cupidDuckkuWhite.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuWhite.imageset/cupidDuckkuWhite@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidDuckkuWhite.imageset/cupidDuckkuWhite@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidGood.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidGood.imageset/cupidGood.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidGood.imageset/cupidGood@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidGood.imageset/cupidGood@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeart.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeart.imageset/cupidHeart.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeart.imageset/cupidHeart@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeart.imageset/cupidHeart@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeartBroken.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeartBroken.imageset/cupidHeartBroken.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeartBroken.imageset/cupidHeartBroken@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidHeartBroken.imageset/cupidHeartBroken@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidPerfect.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidPerfect.imageset/cupidPerfect.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidPerfect.imageset/cupidPerfect@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidPerfect.imageset/cupidPerfect@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStop.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStop.imageset/cupidStop.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStop.imageset/cupidStop@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStop.imageset/cupidStop@3x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStopPress.imageset/Contents.json
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStopPress.imageset/cupidStopPress.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStopPress.imageset/cupidStopPress@2x.png
  playkuround-iOS/Assets.xcassets/ImageAssets/Game/Cupid/cupidStopPress.imageset/cupidStopPress@3x.png
  playkuround-iOS/Resources/StringLiterals.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameView.swift
  playkuround-iOS/Views/Games/CupidGame/CupidGameViewModel.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 서연, UI

#71 [Feat] #70 - 건쏠지식 게임 로직 구현
  playkuround-iOS.xcodeproj/project.pbxproj
  playkuround-iOS/Models/Games/Quiz.swift
  playkuround-iOS/ViewModels/GameViewModel.swift
  playkuround-iOS/ViewModels/RootViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizBlockView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameView.swift
  playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
  playkuround-iOS/Views/Games/QuizGame/QuizState.swift
  playkuround-iOS/Views/Root/RootView.swift
Labels: 서연, Feat

#80 [Fix] #75 - 10초를 맞춰봐 게임 시작 카운트다운 제거
  playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
Labels: 호은, Fix
